version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: aotorichiaki/aotorichiaki:android-ndk26-go1.21
    environment:
      JVM_OPTS: -Xmx7000m
      GRADLE_OPTS: -Dorg.gradle.workers.max=4 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run: echo 'export PATH=/usr/local/go/bin/:${PATH}' >> $BASH_ENV
      - run: go version
      - run: git submodule update --init --recursive
      - run: ./gradlew androidDependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}
      - restore_cache:
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check
      - save_cache:
          paths:
          - ~/go
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
